ifneq ($(filter 3.%,$(MAKE_VERSION)),)
$(error GNU Make version 4.x or higher is required. You are using version $(MAKE_VERSION). Please upgrade your Make installation.)
endif

.DEFAULT_GOAL := all
ROOT_MAKEFILE := $(abspath $(lastword $(MAKEFILE_LIST)))
PROJECT_ROOT := $(patsubst %/,%,$(dir $(ROOT_MAKEFILE)))
GO_TARGET_PREFIX := go.
GO_MODULE_PATHS_EXCLUDE_PATTERNS := ./_examples ./dev ./docs ./tools
GO_MODULE_SLUGS_NO_BETTERALIGN ?= $(GO_MODULE_SLUGS)
GO_TOOLS ?= $(filter-out $(GO_PKG_GRIT) $(GO_PKG_BETTERALIGN),$(GO_TOOLS_DEFAULT))

# N.B. ./make/go.mk includes ./config.mk and ./project.mk if they exist
include $(PROJECT_ROOT)/make/go.mk
# YOU SHOULD NOT / DO NOT NEED TO INCLUDE config.mk OR project.mk HERE

##@ Core Targets

.PHONY: all
all: go.all ## Run a full build of the project.

.PHONY: clean
clean: go.clean ## Tidy up local files generated by the build.

.PHONY: fmt
fmt: go.fmt ## Format all source files.

.PHONY: lint
lint: go.lint ## Lint all source files.

.PHONY: fix
fix: go.fix ## Apply automatic fixes to source files.
	@$(MAKE) --no-print-directory fmt

.PHONY: generate
generate: go.generate ## Generate all code.
	@$(MAKE) --no-print-directory fix

.PHONY: gen
gen: generate ## Alias for 'generate'.

.PHONY: update
update: go.update ## Update all dependencies.

.PHONY: tidy
tidy: go.tidy ## Tidy up go.mod and go.sum files.

up:

test:
	go test ./...

test_v:
	go test -v ./...

test_short:
	go test ./... -short

test_race:
	go test ./... -short -race

test_stress:
	go test -tags=stress -timeout=30m ./...

test_codecov:
	go test -coverprofile=coverage.out -covermode=atomic ./...

test_reconnect:
	go test -tags=reconnect ./...

build:
	go build ./...

wait:

generate_gomod:
	rm go.mod go.sum || true
	go mod init github.com/ThreeDotsLabs/watermill

	go install ./...
	sed -i '\|go |d' go.mod
	go mod edit -fmt

update_examples_deps:
	go run dev/update-examples-deps/main.go

validate_examples:
	(cd dev/validate-examples/ && go run main.go)

##@ -- End of root Makefile --
